workspace:
  base: /go
  path: src/github.com/go-training/drone-golang-example

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: golang:1.9
    pull: true
    commands:
      - make fmt-check
      - go vet
      - go test -v .

  build_linux_amd64:
    image: golang:1.9
    group: build
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -v -a -o release/linux/amd64/helloworld

  build_linux_i386:
    image: golang:1.9
    group: build
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=386
    commands:
      - go build -v -a -o release/linux/amd64/helloworld

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: drone
    username: drone
    icon_url: https://unsplash.it/256/256/?random
    when:
      status: [ success, failure ]
